paths:
  .github/workflows/**/*.{yml,yaml}:
    ignore:
      # Ignore the specific error from shellcheck
      - 'property "test" is not defined in object type.+'
      - 'property "flag" is not defined in object type.+'
      - 'property "text" is not defined in object type.+'
      - 'property "only" is not defined in object type.+'
