name: 'provide-default-inputs-action'
description: 'provide default inputs.'
author: 'srz_zumix'
inputs:
  name:
    description: 'inputs key name. (if empty then all inputs)'
    default: ""
  check-diff:
    description: 'check diff (workflow_dispatch vs workflow_call).'
    default: true
    type: boolean

outputs:
  value:
    description: "default inputs value"
    value: ${{ steps.evalute.outputs.value }}
  json:
    description: "default inputs json file path"
    value: ${{ steps.evalute.outputs.json }}

runs:
  using: node24
  main: dist/main/index.js

branding:
  icon: 'edit-3'
  color: 'purple'
