name: 'provide-default-inputs-action'
description: 'provide default inputs.'
author: 'srz_zumix'
inputs:
  name:
    description: 'inputs key name. (if empty then all inputs)'
    default: ""
  check-diff:
    description: 'check diff (workflow_dispatch vs workflow_call).'
    default: true
    type: boolean

outputs:
  value:
    description: "default inputs value"
    value: ${{ steps.evalute.outputs.value }}
  json:
    description: "default inputs json file path"
    value: ${{ steps.evalute.outputs.json }}

runs:
  using: "composite"
  steps:
    - name: Create default inputs json
      id: evalute
      shell: bash
      env:
        INPUTS_NAME: ${{ inputs.name }}
        INPUTS_CHECK_DIFF: ${{ inputs.check-diff }}
      run: |
        "${{ github.action_path }}/provide-default-inputs.sh"
    
    - name: Set individual outputs from JSON
      id: parse-json
      uses: actions/github-script@v7
      if: ${{ inputs.name == '' }}
      env:
        JSON_VALUE: ${{ steps.evalute.outputs.value }}
      with:
        script: |
          const jsonValue = process.env.JSON_VALUE;
          if (jsonValue && jsonValue !== 'null') {
            try {
              const obj = JSON.parse(jsonValue);
              for (const [key, value] of Object.entries(obj)) {
                core.setOutput(key, value);
              }
            } catch (error) {
              core.warning(`Failed to parse JSON value: ${error.message}`);
            }
          }

branding:
  icon: 'edit-3'
  color: 'purple'
