name: TestSelf(workflow_call)
on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    uses: srz-zumix/provide-default-inputs-action/.github/workflows/test-self.yml@feature/first
    with:
      test: 'test'
      flag: true
      text: 'hoge'
